---
# yamllint disable rule:truthy
name: Test action
on:
  pull_request:
    paths:
      - .github/workflows/test.yaml
      - action.yaml


jobs:

  jfrog-setup-internal-auth:
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: exec jfrog-setup
        id: actual
        uses: ./
        with:
          vaultUrl: https://vault.staging.sonar.build:8200
          artifactoryRoleSuffix: test
      - name: validate
        shell: bash
        run: jfrog rt ping

  jfrog-setup-external-auth:
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: get secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@0a3114fe1230b784c35b53b099f9ab1f1e538cc7 # 3.5.0
        with:
          url: https://vault.staging.sonar.build:8200
          secrets: |
            development/artifactory/token/{REPO_OWNER_NAME_DASH}-test access_token | jf_access_token;
      - name: exec jfrog-setup
        id: actual
        uses: ./
        with:
          jfrogAccessToken: ${{ fromJSON(steps.secrets.outputs.vault).jf_access_token }}
      - name: validate
        shell: bash
        run: jfrog rt ping
