---
# yamllint disable rule:truthy
name: Test action
on:
  pull_request:
    paths:
      - .github/workflows/test.yaml
      - action.yaml


jobs:

  jfrog-setup-internal-auth:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: exec jfrog-setup
        id: actual
        uses: ./
        with:
          vaultUrl: https://vault.staging.sonar.build:8200
          artifactoryRoleSuffix: test
      - name: validate
        shell: bash
        run: jfrog rt ping

  jfrog-setup-external-auth:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: get secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@7461acdbede91679c5c890485f565c80ef74583e # tag=2.4.3-1
        with:
          url: https://vault.staging.sonar.build:8200
          secrets: |
            development/artifactory/token/{REPO_OWNER_NAME_DASH}-test access_token | jf_access_token;
      - name: exec jfrog-setup
        id: actual
        uses: ./
        with:
          jfrogAccessToken: ${{ fromJSON(steps.secrets.outputs.vault).jf_access_token }}
      - name: validate
        shell: bash
        run: jfrog rt ping
